### PR TITLE
 Test Andy's fork Branch

### PR DESCRIPTION
**Pull request by CrossR**

### CODE REVIEW

**Comment by CrossR** [comment]
@AndyChappell  @PandoraPFA 

I believe this is pretty much done now. This includes:

 - Automated check on all commits to main and any PRs that LArContent (and deps) build under g++8  / the latest clang, with/without Monitoring and with/without LibTorch.
 - Cron jobs for Coverity.
 - Disabled clang-format check. We can ignore this, or include it and enable it later, if we want to enforce code formatting in the CI.

The next steps are just smaller ones:

- Pick compiler versions (add more, swap, pin clang version etc?)
- Do we want to try and include a full runtime check ? I.e. we compile all the way through to LArReco, we could try and go the final step, have a test geo and test hits and run a dummy reco job, which is I believe what the previous Dockerfile had included in it. Only unknown there is where those files can live easily.
- The actual setup on the GitHub repo side that I can't do (enable actions, make sure these configs are picked up, setup the variables for Coverity etc).
- Decide if we want or need clang-format enforcement.
- Bring in the changes from Andy and the other tiny patches to actually fix the LibTorch/Monitoring builds. I'd argue that can be done as the very last step. (I.e. we merge the GitHub Actions config, the builds fail, we make a new PR with those changes, the builds pass.) The only concern there is that we'd be enabling the CI on in-progress PRs, though they should arguably be compliant with this anyways.

This PR is just to show the CI output above etc, I'll cherry pick just the config files for a new final PR.

**Comment by AndyChappell** [comment]
Thanks Ryan. I'll have a proper look through this tomorrow, but provisionally:

> * Disabled clang-format check. We can ignore this, or include it and enable it later, if we want to enforce code formatting in the CI.

On the LArSoft side they now enforce clang compliance in the PRs, so there's probably a case to add it here so that we catch such issues internally before they get passed on to the larpandoracontent repo.

**Comment by AndyChappell** [comment]
@CrossR , it looks like your master branch has diverged a little from the PandoraPFA variant (or the clone of my branch needs rebasing, or both), could you either resync your master or possibly just point this at the PandoraPFA repo temporarily so we can isolate the changes from this PR, as I'm seeing all of the DL vertex release changes too. Thanks!

**Comment by AndyChappell** [comment]
Thanks for the updates @CrossR , this is looking good to me.

**Pull request closed without merging**
